# config/services.yaml fusionné
parameters:
    # Tes paramètres (Blockchain/WhatsApp)
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_TOKEN)%'
    twilio_whatsapp_from: '+14155238886'
    
    # Paramètres de tes collègues (Gestion produits)
    products_images_directory: '%kernel.project_dir%/public/uploads/products'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

    App\Controller\BackOffice\:
        resource: '../src/Controller/backOffice/'
        tags: ['controller.service_arguments']